Bump the version to 0.1.5
adjust/first_last_agg pull request #3
Opened 2020-07-16 15:04 UTC by mrimbault

Adds an update script to set aggregate functions to parallel-safe.

2020-07-16 15:49 UTC, alexeyklyukin commented
Does it make sense to include a downgrade script as well, just in case. It should be the same as upgrade, with the versions and the SQL effect reversed.

2020-07-16 16:24 UTC, mrimbault commented
> @mrimbault Does it make sense to include a downgrade script as well, just in case? It should be the same as upgrade, with the versions and the SQL effect reversed.

Well there was no downgrade scripts until that point, but we may as well include one too.
I'll see to add this.

2020-07-16 16:33 UTC, mrimbault commented
@alexeyklyukin done with commit 368e97e9a5233d424d1ce577bbdae96a89b73253

Also, I was wondering, currently we have the plpsql block to mark functions parallel safe at two places:
- the update script
- and the main sql script: https://github.com/adjust/first_last_agg/blob/master/sql/first_last_agg.sql#L24-L49

This means that if anyone just grabs master head and installs the extension using *any version they want*, they'll still get the parallel safe version.
I think we should also remove the plpgsql block from the main sql script, and only keep it on the update script.

2020-07-17 09:08 UTC, mrimbault commented
> Also, I was wondering, currently we have the plpgsql block to mark functions parallel safe at two places:
> 
> * the update script
> * and the main sql script: https://github.com/adjust/first_last_agg/blob/master/sql/first_last_agg.sql#L24-L49
> 
> This means that if anyone just grabs master head and installs the extension using _any version they want_, they'll still get the parallel safe version.
> I think we should also remove the plpgsql block from the main sql script, and only keep it on the update script.

Fixed with commit bcdffce7b1528808ef14c0ae8f5efea39fc3a2c7

Now if we create the extension from a previous version, the functions won't be parallel-safe:
```
postgres=# create extension first_last_agg version '0.1.4' ;
CREATE EXTENSION

postgres=# select proname, proparallel = 's' AS is_parallel_safe from pg_proc where proname in ('first', 'first_sfunc', 'last', 'last_sfunc');
   proname   | is_parallel_safe
-------------+------------------
 first       | f
 first_sfunc | f
 last        | f
 last_sfunc  | f
(4 rows)

postgres=# select aggcombinefn from pg_aggregate where aggfnoid = 'last'::regproc;
 aggcombinefn
--------------
 -
(1 row)
```

Upgrading sets them parallel safe (also works if there are dependencies on other objects):
```
postgres=# alter extension first_last_agg update TO "0.1.5";
ALTER EXTENSION

postgres=# select proname, proparallel = 's' AS is_parallel_safe from pg_proc where proname in ('first', 'first_sfunc', 'last', 'last_sfunc');
   proname   | is_parallel_safe
-------------+------------------
 first       | t
 first_sfunc | t
 last        | t
 last_sfunc  | t
(4 rows)

postgres=# select aggcombinefn from pg_aggregate where aggfnoid = 'last'::regproc;
 aggcombinefn
--------------
 last_sfunc
(1 row)
```

And downgrading works as expected:
```
postgres=# alter extension first_last_agg update TO "0.1.4";
ALTER EXTENSION

postgres=# select aggcombinefn from pg_aggregate where aggfnoid = 'last'::regproc;
 aggcombinefn
--------------
 -
(1 row)

postgres=# select proname, proparallel = 's' AS is_parallel_safe from pg_proc where proname in ('first', 'first_sfunc', 'last', 'last_sfunc');
   proname   | is_parallel_safe
-------------+------------------
 first       | f
 first_sfunc | f
 last        | f
 last_sfunc  | f
(4 rows)

```

2020-09-14 14:25 UTC, mrimbault commented
@alexeyklyukin When you have the time, can you have a look at this PR and see if we could merge it?
Thank you very much :)

2020-09-14 15:42 UTC, alexeyklyukin commented
Hi @mrimbault 

I disagree with the idea of providing parallel-safe aggregates only through an update process; this violates the principle of least surprises, as anyone installing 0.1.5 and expecting first/last aggregates to be parallel-safe will find it not to be the case (and, in addition, everyone updating their master branch and installing extension anew will find the reverse of the parallel-safe flag on the state function). 

If I read the Makefile correctly, we are providing a way to build any version from a single SQL file by changing the default_version in the control file and running make. This seems wrong, as we don't really build the version specified, but instead always build the latest version (by both building the latest version of the  shared library and copying the generic `first_last_agg .sql` into the appropriately named one). Even if, say, we create a SQL file per version and just copy the right one, we may still end up with the C code (always the latest version) being incompatible with the SQL file chosen (the specific version).

So, given that, I propose to abandon the idea that we may somehow "choose" the version we build and instead rely on the git history to pick a previous version when necessary. This means returning back the DO block to the SQL file.

2020-09-14 15:43 UTC, alexeyklyukin requested changes
I'm sorry ti took me almost two months to look into this code, but I think we need to change the SQL file to put the DO block that enables parallel-safe state functions and aggregates back.

2020-09-14 15:45 UTC, alexeyklyukin commented
As another note, not really related to those changes, we should get rid of the `ifeq ($(PG91),yes)` and all the related checks, as the whole thing is too outdated to be of any use.

2020-09-14 16:14 UTC, mrimbault commented
No worries about the delay.
Damn, I was sure that I tested an install directly to the latest version :/
I'll have a look at all of this once again, I'll do a few tests and change the logic so a default install gets the latest version and parallel aggregate working - that's how I intended it to work, I'm not sure how it ended this way :)

2020-09-14 21:24 UTC, mrimbault commented
@alexeyklyukin Reverted, I'm not even sure why I changed it that way.
I've also removed the tests related to pre-9.1 era from the Makefile,

2020-09-16 14:26 UTC, alexeyklyukin approved these changes
Looks good to me, thank you!

2020-09-16 14:35 UTC, merged